import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/layout/header'
import Footer from '@/components/layout/footer'
import Providers from './providers'
import { Tauri } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const tauri = Tauri({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-tauri'
})

/*
Font files can be colocated inside of 'app'
import LocalFont from '<next />
const localFont =  LocalFont({
  src: './my-font.woff2,
  display: 'swap'
})
*/

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${tauri.variable}`}
        suppressHydrationWarning
      >
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
